### ISSUE TITLE
monitoring orb: Add support for AWS

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-ops#149]
in order to setup monitoring for AWS deployed actions, it would be nice if the monitoring orb supports it.

current example:

```yaml
      - helix-post-deploy/monitoring:
          statuspage_name: Microsoft Word Adapter
          statuspage_group: Delivery
          newrelic_group_policy: Delivery Repeated Failure
      - helix-post-deploy/monitoring:
          newrelic_name: "@adobe/helix-word2md.aws"
          newrelic_url: https://$HLX_AWS_API.execute-api.$HLX_AWS_REGION.amazonaws.com/helix-services/word2md/v2/_status_check/healthcheck.json # todo: grab version automatically
          statuspage_name: Microsoft Word Adapter (AWS)
          statuspage_group: Delivery
          incubator: true
          newrelic_group_policy: Delivery Repeated Failure
```

would be nice to write only need to have 1 command with:

```yaml
      - helix-post-deploy/monitoring:
          statuspage_name: Microsoft Word Adapter
          statuspage_group: Delivery
          newrelic_group_policy: Delivery Repeated Failure
          aws_api: $HLX_AWS_API
          aws_region: $HLX_AWS_REGION
```
