### ISSUE TITLE
[monitoring] Add ability to specify monitor locations and frequency

### ISSUE THREAD

**Issue by rofe** [adobe/helix-ops#71]
**Is your feature request related to a problem? Please describe.**
By default, 15 [locations](https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api#list-locations) are configured in a New Relic Synthetics monitor created through the monitoring automation, and there is currently no way to customize them. Also, the frequency is hardcoded to 15 minutes.

**Describe the solution you'd like**
- Add optional arguments `--locations` and `--frequency` to `newrelic`:
```sh
$ node newrelic setup <url> --auth <token> --frequency 5 --locations AW_US_WEST_1, AW_US_EAST_2
```
- Add optional command parameters to `monitoring` command in the `helix-post-deploy` orb:
```yaml
  helix-post-deploy/monitoring:
    newrelic_frequency: 5
    newrelic_locations: AW_US_WEST_1, AW_US_EAST_2
```

**Additional context**
Retrieve a list of valid locations:
```sh
curl -v -X GET -H 'X-Api-Key:<key>' https://synthetics.newrelic.com/synthetics/api/v1/locations
```

**Workaround**
Adjust locations manually in the Synthetics UI.
